spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/jeera_db
spring.datasource.username=jeera_user
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false