-- ─────────────────────────────────────────────────────────────────────────────
-- V1 — baseline schema for Jeera.
--
-- Mirrors the JPA entity model exactly, INCLUDING the columns the legacy
-- CommandLineRunner normalizers used to add to older databases:
--   • users.is_active            (UserSchemaNormalizer)
--   • notifications.project_id   (NotificationSchemaNormalizer)
--   • notifications.issue_id     made nullable (NotificationSchemaNormalizer)
--
-- This script runs only on FRESH databases (CI, new dev, new environments). On
-- the existing production database it never executes: Flyway is configured with
-- baseline-on-migrate=true / baseline-version=1, so the live schema is adopted
-- as the v1 baseline and only V2+ ever run against real data.
-- ─────────────────────────────────────────────────────────────────────────────

create table users (
    id                 bigint generated by default as identity primary key,
    username           varchar(255) not null unique,
    email              varchar(255) not null unique,
    password_hash      varchar(255) not null,
    system_role        varchar(255) not null,
    can_create_project boolean      default false not null,
    is_active          boolean      default true  not null,
    created_at         timestamp(6) not null
);

create table projects (
    id          bigint generated by default as identity primary key,
    name        varchar(255) not null,
    description text,
    owner_id    bigint       not null,
    created_at  timestamp(6) not null
);

create table project_members (
    id           bigint generated by default as identity primary key,
    project_id   bigint       not null,
    user_id      bigint       not null,
    project_role varchar(255) not null,
    added_at     timestamp(6) not null,
    constraint uk_project_member_project_user unique (project_id, user_id)
);

create table issues (
    id              bigint generated by default as identity primary key,
    issue_number    integer      not null,
    project_id      bigint       not null,
    title           varchar(255) not null,
    description     text,
    type            varchar(255) not null,
    priority        varchar(255) not null,
    status          varchar(255) not null,
    reporter_id     bigint       not null,
    assignee_id     bigint,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null,
    closed_at       timestamp(6),
    duplicate_of_id bigint,
    constraint uk_issue_project_issue_number unique (project_id, issue_number)
);

create table comments (
    id         bigint generated by default as identity primary key,
    issue_id   bigint       not null,
    author_id  bigint       not null,
    body       text         not null,
    created_at timestamp(6) not null,
    edited_at  timestamp(6)
);

create table activity_logs (
    id         bigint generated by default as identity primary key,
    issue_id   bigint       not null,
    actor_id   bigint       not null,
    action     varchar(255) not null,
    old_value  varchar(255),
    new_value  varchar(255),
    "timestamp" timestamp(6) not null
);

create table notifications (
    id           bigint generated by default as identity primary key,
    recipient_id bigint       not null,
    message      varchar(255) not null,
    issue_id     bigint,
    project_id   bigint,
    is_read      boolean      not null,
    created_at   timestamp(6) not null
);

-- Foreign keys (added after all tables exist to avoid ordering constraints).
alter table projects        add constraint fk_projects_owner          foreign key (owner_id)        references users (id);
alter table project_members add constraint fk_project_members_project foreign key (project_id)      references projects (id);
alter table project_members add constraint fk_project_members_user    foreign key (user_id)         references users (id);
alter table issues          add constraint fk_issues_project          foreign key (project_id)      references projects (id);
alter table issues          add constraint fk_issues_reporter         foreign key (reporter_id)     references users (id);
alter table issues          add constraint fk_issues_assignee         foreign key (assignee_id)     references users (id);
alter table issues          add constraint fk_issues_duplicate_of     foreign key (duplicate_of_id) references issues (id);
alter table comments        add constraint fk_comments_issue          foreign key (issue_id)        references issues (id);
alter table comments        add constraint fk_comments_author         foreign key (author_id)       references users (id);
alter table activity_logs   add constraint fk_activity_logs_issue     foreign key (issue_id)        references issues (id);
alter table activity_logs   add constraint fk_activity_logs_actor     foreign key (actor_id)        references users (id);
alter table notifications   add constraint fk_notifications_recipient foreign key (recipient_id)    references users (id);
alter table notifications   add constraint fk_notifications_issue     foreign key (issue_id)        references issues (id);
alter table notifications   add constraint fk_notifications_project   foreign key (project_id)      references projects (id);
